DL-4105 - Implement the service timeout
hmrc/employee-wfh-expenses-frontend pull request #18
Opened 2020-09-15 15:23 UTC by jgrath

# JIRA Story DL-4105

## Checklist

*Reviewee* (Replace with your name)
 - [X]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [X]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [X]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message

*Reviewer* (Replace with your name)
 - [ ]  I've confirmed that every effort has been made to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've confirmed appropriate tests has been included with any code added (Unit, Integration, Acceptance etc.)
 - [ ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
 - [ ]  I've confirmed code was added using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [ ]  I've run a dependency check to ensure all dependencies are up to date

2020-09-15 18:27 UTC, grahampaulcook commented on conf/application.conf
> +  timeout = 10
I believe this should be 15 (for 15 minutes)

2020-09-15 18:27 UTC, grahampaulcook commented on conf/application.conf
> +  timeoutCountdown = 3
Need to check but I think the prompt should trigger at 2 minutes before sign-out

2020-09-15 18:29 UTC, grahampaulcook requested changes
Could we change these to default to a safe value, just in case we don't have config values for them.

**FrontendAppConfig.scala**
  lazy val timeoutDialogTimeout: Int = configuration.get[Int]("timeoutDialog.timeout")
  lazy val timeoutDialogTimeoutCountdown: Int = configuration.get[Int]("timeoutDialog.timeoutCountdown")

2020-09-23 11:23 UTC, grahampaulcook commented
@jgrath Could you rebase this PR please as some things have been merged to master

2020-09-24 11:51 UTC, alijy requested changes
- The content on the timeout page needs to be adjusted to adhere to HMRC design
- Add some unit tests for the keep-alive method
- Potential improvement: add a separate controller for keep-alive

2020-09-28 10:11 UTC, alijy requested changes

2020-09-28 10:11 UTC, alijy commented on test/views/SignedOutViewSpec.scala
> +      doc.title() mustBe "For your security, this service has been reset"
This test should be: 
`doc.title() mustBe "For your security, we signed you out"`

2020-09-28 10:57 UTC, alijy approved these changes

2020-09-28 12:17 UTC, merged